FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY *.sln .
COPY MiniStore.API/*.csproj MiniStore.API/
COPY MiniStore.Core/*.csproj MiniStore.Core/
COPY MiniStore.Infrastructure/*.csproj MiniStore.Infrastructure/

RUN dotnet restore

COPY . .
WORKDIR /src/MiniStore.API
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "MiniStore.API.dll"]
